name = "music-shuttle"
compatibility_date = "2024-01-01"
# pages_build_output_dir = "dist"
[assets]
directory = "./dist"


# Environment variables for R2 (Get these from R2 -> Manage R2 API Tokens)
[vars]
R2_ACCOUNT_ID = "351c6b9b5ae8854e9a1842741e95adce"
R2_ACCESS_KEY_ID = "702677513edd2fb1655172facaee43e5"
R2_SECRET_ACCESS_KEY = "65b71f000f22d3ec75ebcd9859f1b247a7767342b4245471aee40cdaa7e7f37d"
R2_BUCKET_NAME = "file-shuttle-bucket"

[[r2_buckets]]
binding = "MUSIC_BUCKET"
bucket_name = "file-shuttle-bucket"

